# Generated by Django 3.2.8 on 2021-11-26 17:52

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211126_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycles',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorcycles',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='motorcycles',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=blog.models.user_directory_path),
        ),
    ]
