# Generated by Django 3.2.8 on 2021-11-27 12:46

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_motorcycles_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycles',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='motorcycles',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_company', to='blog.productioncompany'),
        ),
        migrations.AlterField(
            model_name='motorcycles',
            name='image',
            field=models.ImageField(default='motorcycles/default.jpg', upload_to=blog.models.user_directory_path),
        ),
    ]
